// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD88jiyoEukQRWoIdFau4NrWiRCofJIXQY',
    appId: '1:499754892788:web:4b3cd8fb9c88d9183ccda1',
    messagingSenderId: '499754892788',
    projectId: 'kitahack2026-96d28',
    authDomain: 'kitahack2026-96d28.firebaseapp.com',
    storageBucket: 'kitahack2026-96d28.firebasestorage.app',
    measurementId: 'G-3V614H8C6E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD25EjNU1zmsR23SKrf8aTCGRa9y4uZ64',
    appId: '1:499754892788:android:3cf6174b033363e03ccda1',
    messagingSenderId: '499754892788',
    projectId: 'kitahack2026-96d28',
    storageBucket: 'kitahack2026-96d28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNZrK-1jHT6ylXrX0kb2wv6VX33kJRmlw',
    appId: '1:499754892788:ios:524c7eab89c6ebbd3ccda1',
    messagingSenderId: '499754892788',
    projectId: 'kitahack2026-96d28',
    storageBucket: 'kitahack2026-96d28.firebasestorage.app',
    iosBundleId: 'com.example.kitahack2026',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNZrK-1jHT6ylXrX0kb2wv6VX33kJRmlw',
    appId: '1:499754892788:ios:524c7eab89c6ebbd3ccda1',
    messagingSenderId: '499754892788',
    projectId: 'kitahack2026-96d28',
    storageBucket: 'kitahack2026-96d28.firebasestorage.app',
    iosBundleId: 'com.example.kitahack2026',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD88jiyoEukQRWoIdFau4NrWiRCofJIXQY',
    appId: '1:499754892788:web:4624be91203df21a3ccda1',
    messagingSenderId: '499754892788',
    projectId: 'kitahack2026-96d28',
    authDomain: 'kitahack2026-96d28.firebaseapp.com',
    storageBucket: 'kitahack2026-96d28.firebasestorage.app',
    measurementId: 'G-YGT7HQK23G',
  );
}
